name: Docker Build
env:
      TZ: Asia/Jakarta
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
jobs:

  push-dump-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup minimal environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Run dockerfile repo update script
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "github-actions: $(date +'%d%m%Y')"
          git push "https://${GITHUB_TOKEN}@github.com/greenforce-project/dockerfile" main -f

  ubuntu_toolchain:
    needs: push-dump-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build ubuntu toolchain packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ubuntu/tc
        repository: mhmmdfdlyas/dockerfile
        tags: t-ubuntu

  ubuntu_kernel:
    needs: push-dump-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build ubuntu kernel packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ubuntu/kernel
        repository: mhmmdfdlyas/dockerfile
        tags: k-ubuntu

  ubuntu_rom:
    needs: push-dump-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build ubuntu rom packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ubuntu/rom
        repository: mhmmdfdlyas/dockerfile
        tags: r-ubuntu

  fedora_rom:
    needs: push-dump-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build fedora kernel packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: fedora/kernel
        repository: mhmmdfdlyas/dockerfile
        tags: k-fedora
