name: "Fedora Docker Build"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build kernel packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: fedora/kernel
        repository: mhmmdfdlyas/dockerfile
        tags: k-fedora
