name: build-and-publish

on:
  push:
  schedule:
    - cron: '* * * * SUN'

jobs:
  groovy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dockerfile build push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ubuntu/groovy
        repository: mhmmdfdlyas/dockerfile
        tags: groovy
