name: rom

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  rom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build rom packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ubuntu/rom
        repository: mhmmdfdlyas/dockerfile
        tags: r-ubuntu

    - uses: yanzay/notify-telegram@v0.1.0
      if: always()
      with:
        chat: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        status: ${{ job.status }}
