name: "Ubuntu Docker Build"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
jobs:
  toolchain:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build toolchain packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ubuntu/tc
        repository: mhmmdfdlyas/dockerfile
        tags: t-ubuntu

  kernel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build kernel packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ubuntu/kernel
        repository: mhmmdfdlyas/dockerfile
        tags: k-ubuntu

  rom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build rom packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ubuntu/rom
        repository: mhmmdfdlyas/dockerfile
        tags: r-ubuntu
